### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'xmlns')

### ISSUE THREAD

**Issue by guusdk** [nioc/xmpp-web#120]
### Describe the bug

I'm creating an Openfire plugin that wraps xmpp-web and deploys it in Openfire's embedded web server. This will make deployment of your client into Openfire super simple.

While testing the plugin, and logging in with my own account (lots of roster items, lots of MUC rooms to join), the console log is full of stace traces like this one:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'xmlns')
    at index-0eca49fe.js:15:268250
    at ol.getChildrenByFilter (index-0eca49fe.js:15:237771)
    at xk.parseMessage (index-0eca49fe.js:15:268219)
    at mh.parseStanza (index-0eca49fe.js:15:266731)
    at Ye.emit (index-0eca49fe.js:15:228445)
    at mh._onElement (index-0eca49fe.js:15:245001)
    at Ye.emit (index-0eca49fe.js:15:228386)
    at O2.onEndElement (index-0eca49fe.js:15:251633)
    at Ye.emit (index-0eca49fe.js:15:228386)
    at e2._handleTagOpening (index-0eca49fe.js:15:239931)
```

With my (very) limited javascript skills, I tried clicking through to the source code, which pointed at this line of code:

![image](https://github.com/nioc/xmpp-web/assets/4253898/692ac7f5-13e9-417e-95a1-19171fd01e73)

It appears that this bit of code expectes there always to be an `attrs` property on whatever is being iterated over there?

I'm certainly not ruling out a bug in Openfire here, but it might be good to perform a null-check on `attrs` before trying to access one of its properties.

### Expected behavior

I'm certainly not ruling out a bug in Openfire here, but it might be good to perform a null-check on `attrs` before trying to access one of its properties.

### XMPP-web version

0.10.0

### Installation

Github release archive

### XMPP server(s)

Openfire

### Browser(s)

Chrome

**Comment by nioc** [comment]
This is strange behavior. It implies that some XMPP messages exchanged do not include namespace attribute :astonished:.

Could you post the XMPP messages concerned (from the browser's network>websocket tab)?
![image](https://github.com/nioc/xmpp-web/assets/5225411/b6409752-c7ec-415e-b623-854e565a0dca)
``` xml
<open xmlns='urn:ietf:params:xml:ns:xmpp-framing' version='1.0' xml:lang='en' id='4aaae241-3906-4e7f-b519-a4073cf5bda2' from='mydomain.ltd'/>
```

**Comment by guusdk** [comment]
If I'm reading this correctly, then the data that's being parsed is a newline character only?

![image](https://github.com/nioc/xmpp-web/assets/4253898/a91ea3dd-96e6-4438-aa9f-b43f7035fe76)

**Comment by guusdk** [comment]
There's to much data for me to go through it manually. I'm joined a good deal of chatrooms. Most of them will send message history. I've got about 100 contacts, many of them will send presence. These errors are caught during the initial part of the session (right after logging in) so I do assume it has to do with MAM or presence, but I'm not sure.

The app is hosted at https://xmpp.igniterealtime.org:7483/xmppweb

I'd be happy to provide you with an account on that server, so that you can debug on your own end.

**Comment by nioc** [comment]
Okay I understand, you can provide me a test account, I'll have a look.

Another option: I can provide you a debug version on this thread, if you have the possibility to install it in parallel (another Nginx path) we'll be able to do a more accurate error try catch and see the problematic frame.

**Comment by guusdk** [comment]
Debug output

![image](https://github.com/nioc/xmpp-web/assets/4253898/914bca35-af48-4248-962b-efd3436a0cd8)

**Comment by guusdk** [comment]
Similar issue here:
![image](https://github.com/nioc/xmpp-web/assets/4253898/8fc236e1-bc23-49be-8064-740410a676fb)

**Comment by guusdk** [comment]
I have tested the latest debug build that you left for me last night. It appears to fix the problem!

**Comment by nioc** [comment]
Great news, I'll release it tonight.

**Comment by guusdk** [comment]
Thanks!

We've now created an Openfire plugin for this client: https://discourse.igniterealtime.org/t/new-openfire-plugin-xmpp-web

**Comment by nioc** [comment]
Thanks, it is very kind.

I just have a question about maintenance: How does the plug-in handle web-xmpp updates? I mean, does it has to be updated for each future release or it check/use the latest release at installation/start?

**Comment by guusdk** [comment]
Every update is manual. We do the same for a couple of other web clients. It is a bit of a hassle, but not to bad.

**Comment by nioc** [comment]
Ok 😉
Thanks for it.
