### ISSUE TITLE
Doesn't work with yarn OOTB

### ISSUE THREAD

**Issue by ThatOneCalculator** [nioc/xmpp-web#52]
Steps:

1. Download
2. `yarn install`
3. `yarn run dev`

Error:

```

[plugin:vite:css] Can't find stylesheet to import.
  ╷
3 │ @import "/node_modules/bulma/sass/utilities/_all";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/assets/styles.scss 3:9  root stylesheet

/tmp/xmpp-web/src/assets/styles.scss:3:9

    at Object.wrapException (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:1234:17)
    at /tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:69346:25
    at _wrapJsFunctionForAsync_closure.$protected (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:3726:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:27977:12)
    at _awaitOnObject_closure.call$1 (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:27965:32)
    at Object._rootRunUnary (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:4101:18)
    at StaticClosure.<anonymous> (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:97450:16)
    at _CustomZone.runUnary$2$2 (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:29383:39)
    at _Future__propagateToListeners_handleValueCallback.call$0 (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:28446:51)
    at Object._Future__propagateToListeners (/tmp/xmpp-web/.yarn/cache/sass-npm-1.52.1-7f0eb7e72c-a0508c88b1.zip/node_modules/sass/sass.dart.js:3897:93

Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

```

**Comment by nioc** [comment]
Hi.

I do not know yarn, I use npm.

This works fine on my workstation (ubuntu, node 16):
```
npm install
npm run dev
```

May be I forgot to purge node_modules and it works for me because I got a missing dependency, can you try with npm?

**Comment by ThatOneCalculator** [comment]
Works fine with NPM.

**Comment by nioc** [comment]
Some leads (from the internet 😆):
- `npm install` uses the `package-lock.json` which is provided in the repo, instead of yarn which seems to use `yarn.lock`,
- Yarn installs packages in parallel versus npm will perform a serial installation process.

In the [bulma oruga doc](https://github.com/oruga-ui/theme-bulma#customization-sassscss), the writing is slightly different from mine:
```
@import "~bulma/sass/utilities/_all";
```
As a workaround before I can explain (time for me to go to bed), you can change with this L3 and L86-88.

**Comment by nioc** [comment]
Oh great if it works 😃
